name: buddish_project
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  flutter_redux: ^0.5.2
  redux: ^3.0.0
  http: any
  font_awesome_flutter : any
  shared_preferences: ^0.4.2
  intl: "^0.15.6"
  flutter_youtube: "^1.0.1"
  cached_network_image: "^0.4.1"
  shimmer: ^0.0.4
  audioplayer: ^0.5.0
  path_provider: ^0.4.1
  flutter_launcher_icons: "^0.6.0"
  flutter_masked_text: ^0.5.0

dev_dependencies:
  flutter_stetho: 0.1.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "asset/icon/icon.png"
  android: true 
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/img/login_bg.png
    - asset/logo/camt.png
    - asset/logo/cmu.png
    - asset/logo/med.png
    - asset/logo/mjr.png
    - asset/audio/1.mp3
    - asset/audio/2.mp3
    - asset/audio/3.mp3
    - asset/audio/4.mp3
    - asset/audio/5.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: THSarabunNew
        fonts:
          - asset: fonts/THSarabunNew Bold.ttf
          - asset: fonts/THSarabunNew.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
